# Generated by Django 4.0.4 on 2022-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('instance', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=8)),
                ('team_id', models.CharField(default='', max_length=8)),
                ('team_name', models.CharField(default='', max_length=50)),
                ('player_id', models.CharField(default='', max_length=8)),
                ('player_name', models.CharField(default='', max_length=50)),
                ('goals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoalKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=50)),
                ('saves', models.IntegerField(default=0)),
                ('conceded', models.IntegerField(default=0)),
                ('shots_faced', models.IntegerField(default=0)),
                ('save_percentage', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('one_v_one_won', models.IntegerField(default=0)),
                ('one_v_one_lost', models.IntegerField(default=0)),
                ('penalty_saves', models.IntegerField(default=0)),
                ('penalty_conceded', models.IntegerField(default=0)),
                ('unforced_errors', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('points_per_minute', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('key_passes', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('succ_dribbles', models.IntegerField(default=0)),
                ('unsucc_dribbles', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('shot_target', models.IntegerField(default=0)),
                ('shot_offtarget', models.IntegerField(default=0)),
                ('lost_balls', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=50)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('key_passes', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('succ_dribbles', models.IntegerField(default=0)),
                ('unsucc_dribbles', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('shot_target', models.IntegerField(default=0)),
                ('shot_offtarget', models.IntegerField(default=0)),
                ('lost_balls', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('minutesplayed', models.IntegerField(default=0)),
            ],
        ),
    ]
